# Generated by Django 2.0.1 on 2018-02-07 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('groupname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Hosts',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=50)),
                ('ip', models.GenericIPAddressField()),
                ('port', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=128)),
                ('user_info', models.ForeignKey(on_delete=False, to='Hostmanager.Group')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='host',
            field=models.ManyToManyField(to='Hostmanager.Hosts'),
        ),
    ]
