# Generated by Django 2.0.1 on 2018-02-09 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostmanager', '0002_auto_20180208_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hosts',
            name='group',
        ),
        migrations.AddField(
            model_name='group',
            name='host',
            field=models.ManyToManyField(to='Hostmanager.Hosts'),
        ),
    ]
